app/views/members_views.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_user import current_user, login_required
from app import db, babel
from app.models.user_models import UserProfileForm
from flask import current_app as app
import gettext

members_blueprint = Blueprint('members', __name__, template_folder='templates')


@babel.localeselector
def get_locale():
    translations = [str(translation) for translation in
                    babel.list_translations()]
    return request.accept_languages.best_match(translations)


def set_lang(lang):
    i18n_dir = app.config['BABEL_TRANSLATION_DIRECTORIES']
    gettext.install('lang', i18n_dir)
    trans_file = i18n_dir + lang + '/LC_MESSAGES/flask_user'
    tr = gettext.translation(trans_file, 'locale',  languages=[lang])
    _ = tr.gettext
    app.jinja_env.install_gettext_translations(tr)


@members_blueprint.before_app_request
def before_request():
    lang = get_locale()
    lang = lang if lang else app.config['BABEL_DEFAULT_LOCALE']
    set_lang(lang)

    if request.path.startswith('/admin'):
        if current_user.is_authenticated:
            if not current_user.has_role("admin"):
                return redirect(url_for('user.logout'))
        else:
            return redirect(url_for('user.login'))


@members_blueprint.route('/members/')
@login_required
def member_page():
    return render_template('pages/user_page.html')


@members_blueprint.route('/members/profile/', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    # form = UserProfileForm(request.form, current_user)
    form = UserProfileForm()

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('public.home_page'))

    # Process GET or invalid POST
    return render_template('pages/user_profile_page.html',
                           form=form)

app/views/public_views.py
from flask import Blueprint, render_template, request
import os
from unicodedata import normalize
from flask_user import current_user, login_required


from .youtube import youtube_download
from .transcriber import transcribe
from .upload import upload
# from .transcribe_2 import transcribe

public_blueprint = Blueprint('public', __name__, template_folder='templates')

# @public_blueprint.route('/')
# def home_page():
#     return render_template('pages/home_page.html')
# GLOBALS
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="google_cloud.json"
UPLOAD_FOLDER = 'uploads'
ALLOWED_EXTENSIONS = {'mp3', 'mp4', 'wav'}
HOST = '0.0.0.0'
PORT = 5000
LOCALES = {"ru": "ru-RU", "kz": "kk-KZ", "en": "en-US"}

# CONFIG
# app = Flask(__name__)
# app.config['MAX_CONTENT_LENGTH'] = 200 * 1000 * 1000
# app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
# FUNCTIONS
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS

@public_blueprint.route("/", methods=['GET', 'POST'])
def home_page():
    return render_template('pages/home_page.html')

#https://www.youtube.com/shorts/rz0rvzJL_6U
@public_blueprint.route("/transcribe", methods=['GET', 'POST'])
@login_required
def transcribe_page():
    if request.method == 'POST':
       locale = request.form.get("locale")
       print(f"LOCALE {locale}")
       file = request.files['file']
       if file and allowed_file(file.filename):
           filename = normalize('NFKC',file.filename)
           file_location = f"{UPLOAD_FOLDER}/{filename}"
           print(f"file_location: {file_location}")
           file.save(file_location)
           filename = upload(file_location)
           text, confidence = transcribe(filename, LOCALES[locale])
       elif request.form["youtube"]:
           filename = youtube_download(request.form["youtube"])
           print(filename)
           text, confidence = transcribe(filename, LOCALES[locale])
       else:
           text="Ошибка. Вставьте либо файл, либо ссылку с YouTube"
           confidence = ""
    else:
          text="Запустите приложение для получения транскрипции"
          confidence = ""
    return render_template('pages/transcribe_page.html', data=text)

app/templates/layout.html
{% extends "bootstrap/base.html" %}
{% block title %}This is an example page{% endblock %}
{% import "bootstrap/fixes.html" as fixes %}
{% block head %}
  {{super()}}
  {{fixes.ie8()}}

{% endblock %}

{% block styles %}
  {{super()}}
  <link href="/static/css/global.css" rel="stylesheet">
  
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src=
  "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
  integrity=
  "sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
  crossorigin="anonymous"></script>
  <meta name="viewport" content=
  "width=device-width, initial-scale=1">

{% endblock %}

{% block body %}

  {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/" style="margin-top: 27px;">🐱 {{ user_manager.app_name }}</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse"  style="margin-left: 150px; font-size:20px;">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('public.home_page') }}" style="color: #fff;">{{ _('Home Page') }}</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right" style="margin-right: 10px;">
            {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('members.user_profile_page') }}" style="color: #fff;"><span class="glyphicon glyphicon-user"></span> {{ _('Profile Page') }}</a></li>
              <li><a href="{{ url_for('public.transcribe_page') }}" style="color: #fff;">{{ _('Транскриптор') }}</a></li>
              <li><a href="{{ url_for('user.logout') }}" style="color: #fff;">{{ _('Sign out') }}</a></li>
            {% else %}
              <li><a href="{{ url_for('user.register') }}">{{ _('Register') }}</a></li>
              <li><a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-log-in"></span>  {{ _('Sign in') }}</a></li>
            {% endif %}
          </ul>
          {% if current_user.is_authenticated %}
            {% if current_user.has_role("admin") %}
              <a  class="btn btn-danger navbar-btn"href="{{ url_for('admin.index') }}">{{ _('Admin') }}</a>
            {% endif %}
          {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>

  {% endblock %}



  <div class="container " style="font-size:20px;">
    <div id="main-div" class="with-margins">

      {% import "bootstrap/utils.html" as utils %} {{ utils.flashed_messages(dismissible=True, container=False) }}
      {% block content %}{% endblock %}

    </div>
  </div>

  <footer class="footer">
    <div class="container">
      <p class="text-muted">&copy; <script type="text/javascript">var mdate = new Date(); document.write(mdate.getFullYear());</script>  {{ user_manager.app_name }}</p>
    </div>
  </footer>

  {% block scripts %}
    {{super()}}
  {% endblock %}



{% endblock %}